mysite/credo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from credo import views

app_name = 'credo'

urlpatterns = [
    url(r'^', views.credo, name='credo'),
]

mysite/gdiprofile/urls.py
from django.conf.urls import url, include
from django.urls import path
from gdiprofile import views

app_name = 'gdiprofile'

urlpatterns = [
    url(r'list', views.profile, name='profile'),
    path(r'detail?id=<int:profile_id>', views.profileDetail, name='detail')
]

mysite/googlecalendar/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from googlecalendar import views

app_name = 'googlecalendar'

urlpatterns = [
    url(r'^', views.calendar, name='calendar'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^news/', include('news.urls')),
    url(r'^calendar/', include('googlecalendar.urls')),
    url(r'^profile/', include('gdiprofile.urls')),
    url(r'^credo/', include('credo.urls')),
    url(r'^', include('portal.urls')),

]

mysite/news/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from news import views
from django.urls import path

app_name = 'news'

urlpatterns = [
    url(r'^', views.news, name='news')
]

mysite/portal/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.auth.views import logout
from django.contrib.auth import views
from django.contrib.auth.views import logout_then_login
from . import views
from .views import home

app_name = 'portal'

urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^calendar/', views.calendar, name='calendar'),
    url(r'^login/', views.login, name='login'),
    #url(r'^logout/', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^logout/', views.logout, name='logout'),
    #url(r'^logout/$', lambda request: logout_then_login(request, "/"), name='logout'),
    url(r'^', views.first_page, name='firstPage'),
    #url(r'^logout2/$', django.contrib.auth.views.logout, {'portal':'logged_out.html'}, name='auth_logout'),

    #url(r'^logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    #url(r'^auth/', include('social_django.urls', namespace='social')),
]

mysite/credo/models.py
from django.db import models

# Create your models here.

mysite/portal/models.py
from django.db import models
from django.utils import timezone
from django.contrib import admin
# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
        default=timezone.now)
    published_date = models.DateTimeField(
        blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

mysite/credo/views.py
from django.shortcuts import render

# Create your views here.
def credo(request):
    print('credo')
    return render(request, 'credo/credo.html')

mysite/portal/views.py
from django.shortcuts import render, render_to_response, redirect
from django.template import RequestContext
from django.contrib.auth.views import logout
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.contrib.auth import logout as auth_logout
#from django.contrib.auth import logout
import google_auth_oauthlib.flow
import googleapiclient.discovery
from oauth2client import file, client, tools
from oauth2client.file import Storage
from google_auth_oauthlib.flow import Flow
import google.oauth2.credentials
import httplib2
import os
import requests
from oauth2client.client import flow_from_clientsecrets
from oauth2client.client import OAuth2WebServerFlow

SCOPES = 'https://www.googleapis.com/auth/calendar.readonly'
CLIENT_SECRET_FILE = 'client_secret.json'
APPILCATION_NAME = 'Google Calendar'
CREDENTIAL=""


def set_credentials():
    try:
        import argparse
        flags = tools.argparser.parse_args([])
    except ImportError:
        flags = None
    home_dir = os.path.expanduser('~')
    credential_dir = os.path.join(home_dir, '.credentials')
    if not os.path.exists(credential_dir):
        os.makedirs(credential_dir)
    credential_path = os.path.join(credential_dir, 'calendar-python-quickstart.json')
    store = Storage(credential_path)
    credentials = store.get()
    if True or ( not credentials or credentials.invalid):
        flow = OAuth2WebServerFlow(client_id='1065322067496-bqpqmcirs9u93qt5tl5n5ef4aehne2rp.apps.googleusercontent.com',
                                   client_secret='Kilf5fDJud2oElH3Dgs1PzA6',
                                   scope=SCOPES,
                                   redirect_uri='http://localhost:8000/')
#        flow = flow_from_clientsecrets(CLIENT_SECRET_FILE,
#                                       scope=SCOPES,
#                                       redirect_uri='http://localhost:8000')
        flow.user_agent = APPILCATION_NAME
        credentials = tools.run_flow(flow, store, flags)
        print('Storing credentials to ' + credential_path)
        print(credentials)
    global CREDENTIAL
    CREDENTIAL = credentials


# Create your views here.
def first_page(request):
    return render(request, 'portal/firstPage.html')

def home(request):
    return render(request, 'portal/home.html')

def login(request):
    set_credentials()
    credentials = CREDENTIAL
    http = credentials.authorize(httplib2.Http())
    print('login')
    return render(request, 'portal/home.html')

def logout(request):
    global CREDENTIAL
    credentials = CREDENTIAL
    h = httplib2.Http()
    credentials.revoke(h)
    CREDENTIAL = ""
    print(credentials)
    return render(request,'portal/firstPage.html')

#what is login page

def calendar(request):
    return render(request, 'googlecalendar/calendar.html')

mysite/portal/templates/portal/calendar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
    ul {list-style-type: none;}
    body {font-family: Verdana, sans-serif;}

    /* Month header */
    .month {
        padding: 70px 25px;
        width: 100%;
        background: #1abc9c;
        text-align: center;
    }

    /* Month list */
    .month ul {
        margin: 0;
        padding: 0;
    }

    .month ul li {
        color: white;
        font-size: 20px;
        text-transform: uppercase;
        letter-spacing: 3px;
    }

    /* Previous button inside month header */
    .month .prev {
        float: left;
        padding-top: 10px;
    }

    /* Next button */
    .month .next {
        float: right;
        padding-top: 10px;
    }

    /* Weekdays (Mon-Sun) */
    .weekdays {
        margin: 0;
        padding: 10px 0;
        background-color:#ddd;
    }

    .weekdays li {
        display: inline-block;
        width: 13.6%;
        color: #666;
        text-align: center;
    }

    /* Days (1-31) */
    .days {
        padding: 10px 0;
        background: #eee;
        margin: 0;
    }

    .days li {
        list-style-type: none;
        display: inline-block;
        width: 13.6%;
        text-align: center;
        margin-bottom: 5px;
        font-size:12px;
        color: #777;
    }

    /* Highlight the "current" day */
    .days li .active {
        padding: 5px;
        background: #1abc9c;
        color: white !important
    }

    </style>
</head>
<body>
    <div class="month">
        <ul>
            <li>
                August<br>
                <span style="font-size:18px">2018</span>
            </li>
        </ul>
    </div>

    <ul class="weekdays">
        <li>Mo</li>
        <li>Tu</li>
        <li>We</li>
        <li>Th</li>
        <li>Fr</li>
        <li>Sa</li>
        <li>Su</li>
    </ul>

    <ul class="days">
        <li>1</li>
        <li>2</li>
        <li>3</li>
        <li>4</li>
        <li>5</li>
        <li>6</li>
        <li>7</li>
        <li>8</li>
        <li>9</li>
        <li>10</li>
        <li>11</li>
        <li>12</li>
        <li>13</li>
        <li>14</li>
        <li>15</li>
        <li>16</li>
        <li>17</li>
        <li>18</li>
        <li>19</li>
        <li>20</li>
        <li>21</li>
        <li>22</li>
        <li>23</li>
        <li>24</li>
        <li>25</li>
        <li>26</li>
        <li>27</li>
        <li>28</li>
        <li>29</li>
        <li>30</li>
        <li>31</li>
    </ul>
    <button onclick="goBack()">back</button>

    <script type="text/javascript">
            function goBack(){
                window.history.go(-1);
            }
    </script>
</body>
</html>

mysite/portal/templates/portal/credo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Credo</h1>
<p>私たちGDIコミュニケーションズの社員は

「グローバル・ビジネス・パーソン」として単に

ビジネスをするだけでなく、その活動によって

世界中に笑顔を作り、国際社会の未来のために

必要な解決策と仕組みを提供することを

宣言します。



最前線でグローバルに活躍するからこそ

道徳心を第一に掲げ、利他主義を追求します。



人のために、地球のために一層の努力を重ね、

    組織力と技術力を磨き続けます。</p>


<br>
<ol>1.Theme & Happiness
<br>
生きるテーマと楽しさは、人の道を豊かにするために必要なエッセンス。私たちはすべての仕事にこの要素を加えることを常に心がけます。そして実力を示すための確固たる意志を仲間とともに育みます。人間としての幸福を感じることができれば私たちの事業活動が環境・社会・経済に与える影響をより持続可能（サステナブル）なものへとさせ、より具体的な解決策へ、より地球規模な活動へ繋がると信じています。人の道の豊かさを追求することは、社会の豊かさにつながり、地球愛に変わる。そのための自己研鑚を常に忘れず、なぜ私は働くのかその真理を探求し続けます。
</ol>


<ol>2.Freewill
<br>
想像できるすべてが実現可能。イメージを膨らませたその瞬間に、社会が変わるアイデアが生まれるかもしれない。人間として威風堂々と尊厳を表現し、大きく良い方向へ物事を動かしたければ良心に従い、”Freewill－自由意志”を追求すればいい。私たちは人を尊重し、思いやり、一瞬一瞬を自分の意志で選択して生きています。自由意志から生まれるイノベイティブなアイデアこそ地球全体の繁栄につながり、より良い世界へと変貌を遂げると信じています。
</ol>


<ol>3.Morality
<br>
働き方（目標、時間、場所、報酬）を自由に決められる環境を真に体現している私たち。これは組織や仲間が積み重ねてきた”絶え間ない努力”の賜物。組織は、一人ひとりのモラルの集合体であり、個人の身勝手な行動でいとも簡単にバランスが崩壊してしまうことを理解しています。だからこそ、常にモラリティ高くし、すべてのステークホルダーを大切にし、チームワークを尊守することを誓います。
</ol>


<ol>4.Now or Never
<br>
大いなる成功には常にリスクが伴うことを胸に刻み、失敗を恐れず、勇気をもって挑戦し続けます。できない理由を探したり、失敗の言い訳を考えるのではなく未来の成功に胸を躍らせる人物となります。今やるのか、一生やらないのか。自分を信じ、同調社会に惑わされず、恐れず、自由意志をもって導き出したアイデアを実現させることを誓います。
</ol>


<ol>5.Completing
<br>
真のプロフェッショナルとして日々誰もができる単純なことを当たり前のように継続し、高い目標を掲げ、計画を立て完遂する。流れに身を任せて何もしなければ、当然何も起こらないということを知っています。一見すると実現不可能と見える目標でも、私たちはそれを達成できると信じています。なぜなら、そのために必要なものは何か、私たちは経験から学んでいるからです。それは、同じ志を持った仲間「同志」です。
</ol>

<p>――One day One Smile ☺︎ なんらかのアクションを起こすことで、だれかを笑顔にHappyにさせること。それが私たちの日々のゴールです。</p>
<button onclick="goBack()">back</button>

    <script type="text/javascript">
            function goBack(){
                window.history.go(-1);
            }
    </script>
</body>
</html>

mysite/portal/templates/portal/firstPage.html
<html>
<head>

</head>
<body>
<img src="https://www.gdicommunications.com/images/layout/GDILogo.png"  width="250" height="250">
<p><a href="{% url 'portal:login' %}"> Google Login</a></p>
</body>
</html>

mysite/portal/templates/portal/home.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GDI Portal Site</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <meta name="google-signin-client_id" content="1065322067496-bqpqmcirs9u93qt5tl5n5ef4aehne2rp.apps.googleusercontent.com">
</head>
<body>

<h1>Welcome to GDI Portal Site</h1>
<img src="https://www.gdicommunications.com/images/layout/GDILogo.png"  width="250" height="250">
<br>
    <p><a href="{% url 'news:news' %}">NEWS</a></p>
    <p><a href="{% url 'googlecalendar:calendar' %}">CALENDAR</a></p>
    <p><a href="{% url 'gdiprofile:profile' %}">PROFILE</a></p>
    <p><a href="{% url 'credo:credo' %}">CREDO</a></p>
    <p><a href="{% url 'portal:logout' %}">LOGOUT</a></p>


</body>
</html>

mysite/portal/templates/portal/logged_out.html
<! DOCTYPE html>
<html  lang = "en" >
<head>
    <meta  charset = "UTF-8" >
    <title> Logout </title>
</head>
<body>
<p  class = "display-4" > You logged out. </p>
<a  class= "lead"  href= "{% url 'portal:home' %}"> Home </a>
</body>
</html>

mysite/portal/templates/portal/login.html
{% extends "layout.html" %}
{% block content %}
<a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a><br>
<button onclick="goBack()" ">back</button>

<script type="text/javascript">
        function goBack(){
            window.history.go(-1);
        }
</script>
{% endblock %}

mysite/portal/templates/portal/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <title>GDI Members Profile</title>
</head>
<body>
{% if profile_list%}
    {% for profile in profile_list %}

        {{profile.name}}
        <br>
        {{profile.content}}
        <br>
    {% endfor %}
{% else %}
<p>No data</p>

{% endif %}
<br>
<button>A さん</button>


<button>B さん</button>


<button>C さん</button>

<script>


</script>
</body>
</html>