mysite/gdiprofile/urls.py
from django.conf.urls import url, include
from django.urls import path
from gdiprofile import views

app_name = 'gdiprofile'

urlpatterns = [
    url(r'list', views.profile, name='profile'),
    path(r'detail?id=<int:profile_id>', views.profileDetail, name='detail')
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^news/', include('news.urls')),
    url(r'^calendar/', include('googlecalendar.urls')),
    url(r'^profile/', include('gdiprofile.urls')),
    url(r'^credo/', include('credo.urls')),
    url(r'^', include('portal.urls')),

]

mysite/news/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from news import views
from django.urls import path

app_name = 'news'

urlpatterns = [
    url(r'^', views.news, name='news')
]

mysite/gdiprofile/models.py
from django.db import models
from django.utils import timezone
from django.contrib import admin

# Create your models here.
class Profile(models.Model):
    name = models.CharField(max_length=50)
    content = models.TextField('Content')

mysite/gdiprofile/views.py
from django.shortcuts import render
from .models import Profile

# Create your views here.
def profile(request):
    profile_list = Profile.objects.order_by('name')
    context = {'profile_list': profile_list}
    print('profile')
    return render(request, 'gdiprofile/profile.html', context)

def profileDetail(request,profile_id):
    profile = Profile.objects.get(pk=profile_id)
    return render(request, 'gdiprofile/profileDetail.html', {'profile' : profile})

def DisplayMyPageWithParameter(request, my_parameter):
    parameter = my_parameter
    profile_list = Profile.objects.order_by('name')
    context = {'profile_list': profile_list, 'parameter':parameter}
    return render(request, 'portal/profile.html', context)

mysite/gdiprofile/templates/gdiprofile/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        img{
            width: 350px;
            height: 350px;
        }
    </style>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <title>GDI Members Profile</title>
</head>
<body>
<h1>GDI Members</h1>
{% if profile_list%}
    {% for profile in profile_list %}
        <p><a href="{%  url 'gdiprofile:detail' profile.id  %}">{{profile.name}}</a></p>
    {% endfor %}
{% else %}
<p>No data</p>
<br>
{% endif %}

<br>
<button onclick="goBack()" class="btn btn-warning">back</button>

<script type="text/javascript">
        function goBack(){
            window.history.go(-1);
        }
    </script>
</body>
</html>

mysite/gdiprofile/templates/gdiprofile/profileDetail.html
<h1>{{profile.profile_text}}</h1>

<p>{{profile.name}}</p>
<p>{{profile.content}}</p>

<button onclick="goBack()" class="btn btn-warning">back</button>

<script type="text/javascript">
        function goBack(){
            window.history.go(-1);
        }
</script>